### ISSUE TITLE
Costing

### ISSUE THREAD

**Issue by lgatto** [lgatto/SC-ICS-Proposal#4]
> We normally charge $10K for a one-off instructor training event for non-partners, but I'm sure we could knock it down somewhat for a good cause like this.

@gvwilson could you elaborate on the budget - I think we probably need a bit more details to justify the resource.

**Comment by jduckles** [comment]
@lgatto, @gvwilson asked me to respond to this.

We typically charge $10,000 plus travel expenses. 

Lets knock it down to $8k and then use $2k as a travel budget.

Will that work?

**Comment by lgatto** [comment]
From the ICS page

> We are likely to fund one or two projects with a budget of $20-30k projects, and handful of projects with budgets of  of $5-10k. We do not pay overhead.

Both options are fine, I think.

When you mention travel budget, does this also apply for online training? Would you suggest to have it in person?

**Comment by jduckles** [comment]
No it would not apply for online trainings.  Greg had suggested I give pricing for an in-person event.

The cohorts in online trainings can be 4-8 people at each of up to 3 physical locations, so a total of 12-24 people. The way the instructor training works now we require cohorts of 4 or so people as we have teaching exercises that require peer interactions.

**Comment by lgatto** [comment]
> No it would not apply for online trainings. Greg had suggested I give pricing for an in-person event.

Ok, thanks. Any suggestion on where the course would be organised if we went for an in-person training rather than on-line? How would this be decided?

**Comment by jduckles** [comment]
Perhaps at a major conference of R users?

**Comment by lgatto** [comment]
I have moved the location discussion to issue #9
